### PR TITLE
Upgrade from Go 1.17 to 1.18

### PR DESCRIPTION
**Pull request by lbpdt**
Also upgrade `golang.org/x/sys` dependency to solve a build issue on Go 1.18 - see https://stackoverflow.com/a/71508032.

We are using this project from nixpkgs, which is [failing to build it](https://hydra.nixos.org/build/197511599) with more recent versions of Go. Would be great to cut a new release once this is merged - thanks!

### CODE REVIEW

**Comment by peimanja** [comment]
@lbpdt Thanks for the contribution. Let's also update the go version in the binary release workflow [here](https://github.com/peimanja/artifactory_exporter/blob/master/.github/workflows/release.yml#L25)

**Comment by lbpdt** [comment]
> @lbpdt Thanks for the contribution. Let's also update the go version in the binary release workflow [here](https://github.com/peimanja/artifactory_exporter/blob/master/.github/workflows/release.yml#L25)

Forgot to `grep` over hidden folders - fixed!

**Review by peimanja — APPROVED** [review]
LGTM

**Comment by peimanja** [comment]
@lbpdt  Please check the image with `canary` or `latest` tag and report back if everything is working and I will publish a new release otherwise I will do some testing in a few days

**Comment by lbpdt** [comment]
I was able to test the `latest` image tag successfully 👍

**Comment by lbpdt** [comment]
Thanks for the quick review & release!

**Pull request merged**
